### ISSUE TITLE
Method to remove Workspace folder references from the WorkSpace Folder menu of the Welcome window

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#110]
The only way I can edit the menu is by clearing it and relinking all the workspace folders.

**Comment by ghedlund** [comment]
That is because the workspace history was not designed for that type of fine-grained control. This works like all other file histories in the application. This list was not intended to be 'setup' in this manner (i.e., you are not 're-linking' but 'adding the folder to your history'.)

Do you need this type of control in this list for presentation purposes?  If so you can modify the property for your workspace history in your application preferences file  - I can provide details for this.

**Comment by ghedlund** [comment]
So - what we need the following for all file/folder histories:
 * Ability to view all entries for a history in a list and remove items individually
 * Remove missing items (Either user initiated or automatically)

This includes:
 * Workspace history
 * Project history
 * Open file history
 * Etc.

**Comment by yrose** [comment]
You're suggestion is spot-on!

I was good at keeping my stuff organized but the Workspace menu gets cluttered with artefacts over time, something I've seen in many users. Hence the need for a method. If we could both remove and reorder/or ABC sort them, that would be tremendous!

The other histories aren't as bad; I often clear my project history, and it keeps the most recent things on top, so it's never really overwhelming. And the other two should only show a limited number of options no?

Thank you for thinking about all this :)

Yvan

**Comment by ghedlund** [comment]
Dead entries are now automatically removed from workspace history and recent project list.
