### ISSUE TITLE
Function to assign segment times to unsegmented records

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#153]
Context: series of segmented records with one or more records with 000:00.000-000:00.000 segments scattered within 

Function: assign time intervals based on surrounding record

- If single "0" record between two segmented records, assign time interval based on preceding record's end time (+10ms or something) and following record start time (-10ms)

- If string of several unsegmented records, assign in proportion to the interval available between preceding and following records

**Comment by ghedlund** [comment]
There are two separate actions/paths I think.  The first action can be described as:

1) Distribute Records 
  i) Given start time, end time, set of records.  The start and end times can be a the interval between two records (by number), or the start and end value for the media time. From the Timeline view, the set of records will be the current selection set.
  ii) Adjust segment times by evenly distributing time between given set of records.

2) Fix Clump of Records
This really comes in 2 actions (with the 2nd action performing what you describe if you leave out the first):
  i) Grow records - give them some content
  ii) Layout records contiguously - adjust record times so that the selected records are laid out contiguously in the Timeline.  If records have zero length, 10ms is added to each segment.

**Comment by yrose** [comment]
My sense is we should try to maximally 'fill' the voids between records instead of giving records 10ms (and impractical length). This would mean that the content we're segmenting by assigning these empty intervals to existing records increases the likelihood that the content of the transcribed record be present on the newly-assigned time interval.

This is less true is there is a sequence of records with no intervals assigned, but this is OK.

Key to this request (that we assign time intervals to these in-between, unsegmented records is to then be able to sort records by segment time without altering the original order of the record list.

On Mar 16, 2021, at 10:44 AM, Gregory Hedlund ***@***.******@***.***>> wrote:



There are two separate actions/paths I think. The first action can be described as:

  1.  Distribute Records
i) Given start time, end time, set of records. The start and end times can be a the interval between two records (by number), or the start and end value for the media time. From the Timeline view, the set of records will be the current selection set.
ii) Adjust segment times by evenly distributing time between given set of records.

  2.  Fix Clump of Records
This really comes in 2 actions (with the 2nd action performing what you describe if you leave out the first):
i) Grow records - give them some content
ii) Layout records contiguously - adjust record times so that the selected records are laid out contiguously in the Timeline. If records have zero length, 10ms is added to each segment.
