### ISSUE TITLE
New Stock Reports for Listing Results

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#17]
After a Data Tiers query that adds tiers to the results, current listing by session shows a record by line, with each data tier listed as columns. Example:

| Session  | Speaker | Age          | Record #  | Morpheme Type  | Orthography (Group)  | TMorph (Group) |
| 06           | Ani         | 02;03.24  | 628   pvb   chîh=miyw=ây=i=u   ʧɪ=miˈj=a=j=o   ˈdu=n=a=j=o |

In most cases, listings by session should be formatted in a more vertical way, closer to a record-like view, something like:

Session  | Speaker | Age          | Record # | Tier                               | Result
06           | Ani         | 02;03.24 | 628          | Orthography (Group)  | chîh=miyw=ây=i=u
                |         	|                 |                 | TMorph (Group)           | pvb=initial=medial=vii.fin=IIN

 - If it's easier, we can list all data on all lines (here, Session, Speaker, Age and Record #)
 - The distinction "by Session" follows the same logic as for our current "Listing" layouts

----

Todo:

 * [X] Update 'Session to HTML' to include options for printing query results
 * [x] Create new 'Results to HTML' node 
 * [x] Create new 'Print Results' query report

**Comment by ghedlund** [comment]
This will not work - it violates rules with CSV table exports and tables generated in this fashion are not usable in the analysis pipeline.

**Comment by ghedlund** [comment]
Ok, so currently we do use Tables for displaying the data.  What is requested here is to display result data, row by row, as a key-value pair.  (In essence flipping table orientation and with each row becoming it's own table.)  So, something like:

| Session | Age | Record | Result | Notes |
|---|---|---|---|---|
| One | 2.5 | 1 | hello | test |
| One | 2.5 | 2 | world | ing |

Would become:

| Session | One |
|--|--|
| Age | 2.5 |
| Record | 1 |
| Result | hello |
| Notes | test |

| Session | One |
|--|--|
| Age | 2.5 |
| Record | 2 |
| Result | world |
| Notes | ing |

A more appropriate output may be better due to the redundancy of the output, however it depends on how the report data will be used (e.g., read or pumped into another program.)  If data is being used in another program it would be best to use the current table output in our reports.

## Session One
Age: 2.5

 1. Record: 1
     * Result: hello
     * Notes: test

 2. Record 2
     * Result: world
     * Notes: ing

**Comment by yrose** [comment]
The layout you are suggesting however implies a whole lot of redundancies, so I am not sure how useful it might be in the end. By and large, for human reading/analysis of Phon record data obtained through queries, the closest we could get to record views the better it would be.

**Comment by ghedlund** [comment]
Todo:

 * [ ] Create new 'Format Table' opgraph node.
    - Needs to support multiple 'group by' columns (e.g., Session + Age/Speaker)
    - Needs a list of included/excluded columns
 * [ ] Rename existing 'Listing' and 'Listing by Session' as 'Table' and 'Table by Session' and update documentation.
 * [ ] Create new 'Listing' and 'Listing by Session' reports using the new 'Format Table' node
 * [ ] Update default report to use new 'Listing' reports?
