### ISSUE TITLE
Morpheme Markers

### ISSUE THREAD

**Issue by ghedlund** [phon-ca/phon#81]
We currently have API methods for accessing records data in aligned groups, words, and syllables (for IPA tiers).  A method for marking morpheme boundaries in tiers (preferably without using printable characters) needs to be added.  These markers will be stored in a morpheme marker extension (storage of this data will require new session IO) and new API methods for accessing aligned morphemes across tiers needs to be created.

**Comment by yrose** [comment]
A visual marker may be useful from a user's standpoint (for analysis), unless we use colouring or other types of cues. 
CHAT uses ~ (tilde) as clitic/morpheme boundary marker. When we export CCLAS data to CHILDES, we convert the = of CCLAS by ~ in CHAT.

**Comment by ghedlund** [comment]
For UI the idea would be for the user to place the cursor at the correct location in a tier and use either a button or keystroke to create/remove morpheme markers.  The marker could then be made visible to the user - e.g., a small blue triangle will appear at the correct location.

Re: CCLAS - Phon actually supports the '~' character in Orthography tier - and support could easily be added to the IPA tiers (right now I would use + in it's place.)  Perhaps it would be a good idea to switch this over in the Phon files as well?

**Comment by yrose** [comment]
I like the blue triangle idea; we must also think of an equivalent in printed reports, data exports, etc.

CCLAS: I believe we are not supporting + because it's a good marker for compounds (e.g. truck+driver). Tilde works great as morpheme marker (e.g. truck+driver~s)

CHAT/CLAN (input from Brian): CHAT relies on the %mor tier for morphological analysis, rather than the main line.  The main line presents words in their standard orthography.  On the %mor line the dash  (-) represents a productive morphemic boundary.  The ampersand & represents fusional morphology.  The tilde represents cliticization and the # sign represents prefixation.  These symbols will certainly be enough for Turkish.  I don’t know about Cree.  On the other hand, if you are talking about introducing a new set of symbols for the main line, then we have tried to avoid that.  It might be possible, but it would require some thinking and understanding about why it is necessary.  Things like this are described in the MOR manual.
