### ISSUE TITLE
Screen-less mode for Media player 

### ISSUE THREAD

**Issue by yrose** [phon-ca/phon#84]
Most users utilize audio files, but must maintain the VLC 'screen' in their interfaces. Could the screen show up only when it's needed (i.e. when video is used)?

**Comment by ghedlund** [comment]
The screen for the media player has no minimum size.  When playing audio the 'screen' is essentially a space filler as the size of the component is decided by the row the view resides in.  You can reduce the media screen to zero by placing the media view into a row with no other views and reducing the size of the row to match the player controls.

![Screen Shot 2020-03-05 at 5 57 23 PM](https://user-images.githubusercontent.com/866552/76027189-c8b77780-5f0a-11ea-9b76-070a75bccf05.png)

The media player can also be 'minimized' into one of the NESW bar positions so that it can be hidden from the UI while still present in the view hierarchy.

![Screen Shot 2020-03-05 at 5 58 52 PM](https://user-images.githubusercontent.com/866552/76027314-fbfa0680-5f0a-11ea-98bd-9907785a0cce.png)

**Comment by yrose** [comment]
OKdoke! I'll add these notes to documentation when I get to this task.

**Comment by ghedlund** [comment]
Media player will no longer be required for audio playback of segments/selection in the Timeline view.  If the video player is available and the loaded media has video only playback of the segment will also occur.  This also fixes the issue of the playback marker moving past the segment boundary.

**Comment by ghedlund** [comment]
The above comment now also applies to the Speech Analysis view.
